apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  labels:
    app: geohospital

spec:
  selector:
    app: geohospital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000